### ISSUE TITLE
Weird Duplicated Ability with grenade launcher

### ISSUE THREAD

**Issue by wdanny69** [Grobobobo/WarOfTheChosenRebalanced#38] opened 2022-06-20 19:56 UTC
When using the grenade launcher, one of the grenades (haven't figured out how it works) is sometimes duplicated (doesn't grant more charges, just the same one but not affected with the launcher or something) or just a weird creation of a blank one

https://youtu.be/61Lk1aAbfPI

**Comment by Grobobobo** [comment] 2022-06-22 09:37
This is probably a duplicate of #13.

**Closed as completed** 2022-06-28 16:03 UTC
